config/routes.rb
Rails.application.routes.draw do
  resources :urls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "urls#new"

  get '/shortened_url' => 'urls#shortened_url'
  get '/:id', to: 'urls#decode_url'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/shorten_url.rb
module ShortenUrl
  ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split(//)
    
  def bijective_encode(i)
    # from http://refactormycode.com/codes/125-base-62-encoding
    # with only minor modification
    return ALPHABET[0] if i == 0
    s = ''
    base = ALPHABET.length
    while i > 0
      s << ALPHABET[i.modulo(base)]
      i /= base
    end
    s.reverse
  end

  def bijective_decode(s)
    # based on base2dec() in Tcl translation 
    # at http://rosettacode.org/wiki/Non-decimal_radices/Convert#Ruby
    i = 0
    base = ALPHABET.length
    s.each_char { |c| i = i * base + ALPHABET.index(c) }
    i
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]
  include ShortenUrl
  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def shortened_url
    org_url = params[:url]
    url = Url.create(original_url: org_url)
    short_url = "http://localhost:3000/" + bijective_encode(url.id)
    url.short_url = short_url
    url.save
    render json: { status: 200, short_url: short_url }
  end

  def decode_url
    encoded_param = params[:id]
    id = bijective_decode(encoded_param)
    url = Url.find(id)
    redirect_to url.original_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:original_url, :short_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :original_url %>
    <%= form.text_field :original_url %>
  </div>

  <div class="field" id='short-url-panel'>
    <%= form.label :short_url %>
    <span id='short-url-value'></span>
  </div>

  <div class="actions">
    <%= form.submit id: 'generate-url' %>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    var $originalurl = $('#url_original_url');
    var $shortUrl = $('#url_short_url');
    var $shortUrlVal = $('#short-url-value');
    var $shortUrlPanel = $('#short-url-panel');
    $shortUrlPanel.hide();
    $(document).on('click', '#generate-url', function(e){
      e.preventDefault();
      if(isValidUrl($originalurl.val())){
        sendRequest();
      }
      else {
        alert("Please add valid URL");
      }
    });

    function isValidUrl(url){
      var pattern = /^(http|https)?:\/\/[a-zA-Z0-9-\.]+\.[a-z]{2,4}/;
      return pattern.test(url);
    }

    function sendRequest(){
      $.ajax({
        url: '/shortened_url',
        data: {url: $originalurl.val()},
        success: function(result){
          $shortUrlPanel.show();
          $shortUrlVal.text(result.short_url);
        }
      });
    }

  });

</script>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Original url</th>
      <th>Short url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.original_url %></td>
        <td><%= url.short_url %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original url:</strong>
  <%= @url.original_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @url.short_url %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>